/**
 * content.js — the copy that ships regardless.
 *
 * `src/tutorial.js` is an optional module that can replace all of this with
 * something richer. This file exists so the app is never *missing* its guidance
 * — a font-making tool whose help text fails to load is worse than useless,
 * because the advice here is the difference between a good sample and a bad
 * one, and the user only finds out which they produced at the very end.
 */

export const FALLBACK_LESSONS = [
  {
    id: 'what',
    title: 'What you are about to do',
    body: [
      'You will copy about 120 characters onto blank paper, photograph the page, and get back a font of your own handwriting that you can install and type with.',
      'The whole thing runs inside this browser tab. Your photograph is read here, the letters are traced here, and the font file is written here. Nothing is uploaded and there is no account.',
    ],
  },
  {
    id: 'pen',
    title: 'Pick the right pen',
    illustration: 'pen',
    body: [
      'A fine-liner or gel pen around 0.5 mm gives the cleanest result. The ink needs to be clearly darker than the paper.',
    ],
    tips: [
      'Avoid pencil — it photographs faint, and graphite catches the light unevenly.',
      'Avoid broad markers — thick strokes merge into blobs that cannot be separated back out.',
      'Use the same pen for the whole set. Switching pens halfway shows up as uneven weight.',
    ],
  },
  {
    id: 'writing',
    title: 'Write the way you actually write',
    body: [
      'People instinctively switch to careful block capitals the moment they know something is being recorded. Resist that. It produces a stiff, generic font that does not look like you.',
      'Write at your natural size and your natural speed. Slight inconsistency is what makes handwriting read as handwriting.',
    ],
    tips: [
      'Let tall letters run tall and tails run long — the app reads your baseline from them.',
      'Do not try to make every letter identical. The font deliberately varies them anyway.',
    ],
  },
  {
    id: 'gaps',
    title: 'Leave gaps between characters',
    illustration: 'spacing',
    body: [
      'This is the one thing the app cannot fix for you. Rotation, shadows, uneven lighting and page skew are all corrected automatically — but two characters written so they touch are read as a single shape.',
      'A gap about the width of one letter is plenty. Keep rows well separated too, so a descending tail does not run into the row below.',
    ],
  },
  {
    id: 'photo',
    title: 'Photographing the page',
    illustration: 'photo',
    body: [
      'Lay the paper flat, light it evenly, and shoot straight down. Indirect daylight near a window works better than a desk lamp, which throws a hard shadow across one side.',
      'You do not need to line the photo up carefully. The page is straightened automatically, and lighting is corrected per-region rather than with one global threshold, so a shadow across a corner is not a problem.',
    ],
    tips: [
      'Avoid casting your own shadow over the page while shooting.',
      'A flatbed scan works too, if you have one.',
    ],
  },
  {
    id: 'styles',
    title: 'Bold and italic are handled for you',
    body: [
      'You only write once. Bold is generated by thickening your outlines along their own edges, and italic by shearing them, so all four styles come from the single sample and stay recognisably one hand.',
      'Because they share a family name, pressing Bold or Italic in a word processor switches between them normally. You do not pick them from the font menu by hand.',
    ],
  },
  {
    id: 'variants',
    title: 'Why your letters will not look identical',
    body: [
      'Real handwriting never repeats a letter exactly, and a font that does is instantly recognisable as fake. Every character is built in three slightly different versions that rotate as you type.',
      'So the word "letter" shows three different t\'s. This is a standard OpenType feature and you can turn it off in the Refine step or later in any design app.',
    ],
  },
];

export const FALLBACK_INSTALL = [
  {
    os: 'windows',
    label: 'Windows',
    steps: [
      'Open the downloaded zip and extract it.',
      'Select all four .otf files together.',
      'Right-click the selection and choose "Install".',
      'Restart any app that was already open — running apps do not pick up new fonts.',
    ],
    note: 'If you see "Install for all users", that works too and needs an administrator.',
  },
  {
    os: 'macos',
    label: 'macOS',
    steps: [
      'Open the downloaded zip.',
      'Select all four .otf files and drag them into Font Book.',
      'Or double-click each file and press "Install Font".',
      'Restart any app that was already open.',
    ],
  },
  {
    os: 'linux',
    label: 'Linux',
    steps: [
      'Extract the zip.',
      'Copy the four .otf files into ~/.local/share/fonts/ (create it if missing).',
      'Run: fc-cache -f -v',
      'Restart the apps you want to use it in.',
    ],
  },
  {
    os: 'ios',
    label: 'iOS',
    steps: [
      'iOS cannot install a font from the Files app on its own.',
      'You need an app that installs fonts as a configuration profile — there are several free ones on the App Store.',
      'Open the .otf through that app, then approve the profile in Settings.',
      'The font then appears in Pages, Keynote and other apps that support custom fonts.',
    ],
    note: 'This is an iOS restriction, not something this app can work around.',
  },
  {
    os: 'android',
    label: 'Android',
    steps: [
      'Most Android apps cannot use custom fonts at all.',
      'Some launchers, note-taking apps and design apps can load an .otf directly — check that app\'s own settings.',
      'Rooted devices can install system-wide, but that is beyond what this guide covers.',
    ],
    note: 'The web font files in the zip may be more useful on Android than the .otf.',
  },
];

export const FALLBACK_FAQ = [
  {
    q: 'Is my handwriting uploaded anywhere?',
    a: 'No. Every step — reading the photo, tracing the letters, building the font — happens in this browser tab. There is no server involved and no network request after the page loads.',
  },
  {
    q: 'Who owns the font?',
    a: 'You do, completely. There is no licence to follow and no attribution required. You can use it commercially or sell it.',
  },
  {
    q: 'Why is it a .otf and not a .ttf?',
    a: 'Both are OpenType fonts and install identically everywhere. The .otf format carries cubic Bézier outlines, which is exactly what the tracer produces, so nothing is lost converting between curve types.',
  },
  {
    q: 'Can I add more characters later?',
    a: 'Not to an existing font, but making another takes only a few minutes — write the extra sheet and run it again.',
  },
];
