/**
 * tutorial.js — the guidance shown before a pen is picked up.
 *
 * Exported as data, not markup, for the reason the field spec gives: the shell
 * renders it, and keeping it as data means the same sentences can appear in
 * onboarding, in contextual help, and in the README written into the exported
 * zip without three copies drifting apart.
 *
 * This deliberately replaces the leaner set in content.js. The single highest
 * value this app has is telling someone what makes a good sample *before* they
 * fill four sheets badly, so the copy leans into the few things that actually
 * decide whether the font comes out looking like the writer's hand.
 *
 * House constraints followed here: every body paragraph stays under about forty
 * words because it is read one-handed by someone holding a pen; sentence case,
 * no exclamation marks, no marketing voice.
 */

export const LESSONS = [
  {
    id: 'what',
    title: 'What you are about to do',
    body: [
      'You copy about 120 characters onto paper, photograph the page, and get back a font of your own handwriting that you can install and type with.',
      'Everything runs inside this browser tab. Nothing is uploaded and there is no account. The one thing the page still needs the network for is fetching its own code — parts of the app load on demand the first time you reach them.',
    ],
  },
  {
    id: 'pen',
    title: 'Pick the right pen',
    illustration: 'pen',
    body: [
      'A fine-liner or gel pen around 0.5 mm gives the cleanest result. What matters is that the ink comes out clearly darker than the paper.',
    ],
    tips: [
      'Not pencil. It photographs faint, and graphite catches the light so the same stroke reads dark in one place and pale in another.',
      'Not a broad marker. Thick strokes merge into blobs that cannot be separated back into letters.',
      'Use one pen for the whole set. Switching partway shows up as uneven weight across the font.',
    ],
  },
  {
    id: 'natural',
    title: 'Write the way you actually write',
    body: [
      'People switch to careful block capitals the moment they know something is being recorded. Resist that. It produces a stiff, generic font that does not read as yours.',
      'Write at your natural size and speed. The slight inconsistency between one letter and the next is exactly what makes handwriting look handwritten.',
    ],
    tips: [
      'Let tall letters run tall and tails run long. The app reads your baseline from how far they reach.',
      'Do not try to make each letter identical. Three variants per character rotate as you type, so sameness is added back deliberately, not lost.',
    ],
  },
  {
    id: 'touching',
    title: 'Keep characters from touching',
    illustration: 'spacing',
    body: [
      'This is the one failure the app cannot repair. Skew, rotation, shadows and uneven light are all corrected for you, but two characters written so they touch are read as a single shape.',
      'A gap about the width of one letter is plenty. Keep rows well apart too, so a descending tail does not run into the line below.',
    ],
  },
  {
    id: 'photo',
    title: 'Photographing the sheet',
    illustration: 'photo',
    body: [
      'Lay the paper flat, light it evenly, and hold the camera parallel to the page. Indirect daylight works better than a desk lamp, which throws a hard shadow across one side.',
      'You do not need to line the shot up carefully. The page is straightened automatically and lighting is corrected region by region, so a shadow across a corner is fine.',
    ],
    tips: [
      'Do not let your own shadow fall across the page while you shoot.',
      'A flatbed scan works just as well if you have one.',
    ],
  },
  {
    id: 'baseline',
    title: 'Why the boxes are only for you',
    illustration: 'baseline',
    body: [
      'If you use the printable sheet, the guide boxes are printed in light blue on purpose. That blue drops out when the photo is processed, so the boxes never end up traced into your letters.',
      'So write freely inside them. The dotted baseline and dashed mid-line are there to keep your sizing steady, not to be photographed.',
    ],
  },
  {
    id: 'styles',
    title: 'Bold and italic come for free',
    body: [
      'You write the alphabet once. Bold is generated by thickening your outlines along their own edges, and italic by shearing them, so all four styles come from the single sample.',
      'Because they share a family name, pressing Bold or Italic in a word processor switches between them normally. You do not pick them from the font menu by hand.',
    ],
  },
];

/**
 * Install guidance. The app auto-detects the platform and looks the entry up by
 * `os`, so all five values must be present or that user is left with nothing.
 * Accuracy over reassurance here: iOS and Android genuinely cannot do what the
 * others can, and saying so plainly beats letting people fail silently.
 */
export const INSTALL = [
  {
    os: 'windows',
    label: 'Windows',
    steps: [
      'Open the downloaded zip and extract it somewhere.',
      'Select all four .otf files together.',
      'Right-click the selection and choose Install.',
      'Restart any app that was already open. Running apps do not pick up a new font until they are relaunched.',
    ],
    note: 'The "Install for all users" option works too, but it needs administrator rights.',
  },
  {
    os: 'macos',
    label: 'macOS',
    steps: [
      'Open the downloaded zip.',
      'Select all four .otf files and drag them into Font Book.',
      'Or double-click each file in turn and press Install Font.',
      'Restart any app that was already open so it sees the new family.',
    ],
  },
  {
    os: 'linux',
    label: 'Linux',
    steps: [
      'Extract the zip.',
      'Copy the four .otf files into ~/.local/share/fonts/ and create that folder if it is missing.',
      'Run fc-cache -f -v to rebuild the font cache.',
      'Restart the apps you want to use the font in.',
    ],
    note: 'A system-wide install goes in /usr/local/share/fonts/ instead and needs root.',
  },
  {
    os: 'ios',
    label: 'iOS',
    steps: [
      'iOS cannot install a font from the Files app on its own.',
      'You need a font-installer app that adds the font as a configuration profile. Several free ones are on the App Store.',
      'Open the .otf through that app, then approve the profile in Settings.',
      'The font then appears in Pages, Keynote and other apps that support custom fonts.',
    ],
    note: 'This is an iOS restriction, not something this app can work around.',
  },
  {
    os: 'android',
    label: 'Android',
    steps: [
      'Most Android apps cannot use a custom font at all.',
      'Some launchers, note-taking apps and design apps can load an .otf directly. Check that app’s own settings.',
      'Installing system-wide needs a rooted device, which is beyond what this guide covers.',
    ],
    note: 'The web-font files included in the zip are often more useful than the .otf on Android.',
  },
];

/**
 * The questions people actually ask, kept short. The privacy answer comes first
 * because it is the one that decides whether they trust the tool at all.
 */
export const FAQ = [
  {
    q: 'Is anything I write uploaded?',
    a: 'No. Reading the photo, tracing the letters and building the font all happen in this browser tab, and there is no server involved in any of it. The network is used for one thing only: fetching the app’s own code, some of which loads on demand the first time you reach it.',
  },
  {
    q: 'Who owns the font?',
    a: 'You do, entirely. There is no licence to follow and no attribution required. You can use it commercially or sell it.',
  },
  {
    q: 'Why is it a .otf and not a .ttf?',
    a: 'Both are OpenType and install identically everywhere. The .otf format carries cubic Bezier outlines, which is exactly what the tracer produces, so nothing is lost in conversion.',
  },
  {
    q: 'Why do my letters look slightly different each time?',
    a: 'That is deliberate. Each character is built in three slightly different versions that rotate as you type, so repeated letters do not look rubber-stamped. You can switch it off in the Refine step.',
  },
  {
    q: 'Do I have to write everything four times for the styles?',
    a: 'No. You write once. Bold and italic are synthesised geometrically from that single sample, so all four styles stay recognisably one hand.',
  },
  {
    q: 'How is letter spacing decided?',
    a: 'It is measured, not guessed. Handwrite reads the ink profile down each side of every character and sets its bearings so the perceived gap between any two letters comes out even. A round o already carries space in its own curve where a flat H carries none, so giving them identical margins — which is what most handwriting fonts do — makes one look loose and the other cramped.',
  },
  {
    q: 'What is kerning, and do I need it?',
    a: 'Kerning is a per-pair correction on top of normal spacing, for combinations that collide or gape no matter how well each letter is spaced on its own — AV, To, Wa, r. and f) are the usual offenders. It is generated automatically and you can switch it off in the Refine step, though there is rarely a reason to.',
  },
  {
    q: 'The spacing looks wrong. What do I change?',
    a: 'Use the spacing slider in the Refine step and type a line with a lot of round letters next to straight ones. If only one or two characters look wrong rather than the whole line, the cause is usually that glyph itself — go back to Review and redraw it, since a stray speck or a clipped edge shifts where its bearings land.',
  },
  {
    q: 'Why do the words run together, or sit too far apart?',
    a: 'That is the width of the space character, which is derived from the width of your lowercase letters rather than written by hand. The spacing slider in the Refine step moves it along with everything else.',
  },
];
